[package]
name = "swissknife"
version = "0.0.1"
edition = "2021"
authors = ["Jiran Kurian <jirankurian@gmail.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
