[package]
name = "swissknife"
version = "0.0.1"
edition = "2021"
authors = ["Jiran Kurian <jirankurian@gmail.com>"]
description = "A versatile utility tool set for Rust"
license = "Apache-2.0"
repository = "https://github.com/jirankurian/swissknife"